name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: test
      run: docker run -w /workdir -v $(pwd):/workdir haskell:8.0.2 stack test --allow-different-user
