name: test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v1.1.0
      with:
        path: /workdir
        key: workdir
    - run: docker run -w /workdir -v $(pwd):/workdir -it haskell:8.0.2 stack test
