name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ["8.0.2"]
        cabal: ["1.24"]

    steps:
    - uses: actions/checkout@v1
    - name: setup
      uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - uses: mstksg/setup-stack@v1
    - name: test
      run: stack --system-ghc test
