name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: haskell:8.0.2
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1.1.0
      with:
        path: $(pwd)
        key: cache
    - run: |
        TAR_OPTIONS=--no-same-owner stack setup
        stack test --allow-different-user
