name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: haskell:8.0.2
      volumes:
        - volume:/volume
    env:
      TAR_OPTIONS: --no-same-owner
    steps:
    - uses: actions/checkout@v2
    - name: cache
      uses: actions/cache@v1.1.0
      with:
        path: /volume
        key: volume
    - run: stack test
