name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1
      with:
        docker_version: 19.03
    - run: docker run -w /workdir -v $(pwd):/workdir -it haskell:8.0.2 stack test
